name: Obfuscate and Version Update

on:
  push:
    branches: ['main', 'Dev']
    paths:
      - '**/index.*'
      - '**/obfs.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install javascript-obfuscator
        run: npm install -g javascript-obfuscator

      - name: Obfuscate index.js
        run: |
          javascript-obfuscator index.js --output _worker.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 1 \
            --dead-code-injection true \
            --dead-code-injection-threshold 1 \
            --identifier-names-generator hexadecimal \
            --rename-globals false \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 1 \
            --transform-object-keys true \
            --unicode-escape-sequence true

      - name: Add multiline version comment to index.js
        run: |
          if [ -s index.js ]; then
            VERSION_BLOCK="/*\n * Last update: $(date -u '+%Y-%m-%d %H:%M:%S') UTC\n * We are all REvil - version based on commit ${{ github.sha }}\n */"
            if grep -q "Last update:" index.js; then
              awk '/Last update:/ {print "'"$VERSION_BLOCK"'"; skip=1; next} /^\s*\*\/$/ && skip {skip=0; next} !skip' index.js > temp.js && mv temp.js index.js
            else
              echo -e "$VERSION_BLOCK\n\n$(cat index.js)" > temp.js && mv temp.js index.js
            fi
          else
            echo "⚠️ index.js is missing or empty. Skipping version comment insertion."
          fi
    
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _worker.js index.js
          git commit -m "Automated build: obfuscation and version update" -m "Based on commit ${{ github.sha }}" || echo "No changes to commit."
          git push origin ${{ github.ref }}
