name: Add Version Comment

on:
  push:
    branches: ['main', 'DEV']
    paths:
      - '**/index.*'
      - '**/obfs.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version-comment:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Modify version worker-vless.js
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: _worker.js
          body: "Last update: {{date:YYYY-MM-DD HH:mm:ss}} UTC - REvil - version base on commit ${{ github.sha }} "
          message: "Version Comment add successfully"
          
