name: Add Version Comment

on:
  push:
    branches: [main]
    paths:
      - '**/index.*'
      - '**/obfs.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version-comment:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Modify worker code version
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: index.js
          body: "Last update: {{date:YYYY-MM-DD HH:mm:ss}} UTC - We are all REvil - version base on commit ${{ github.sha }} "
          message: "Version Comment add successfully"
          
